#!/bin/sh
set -e

case "$1" in
    install|configure)
        vdicfg="/etc/linuxmuster/linbo-vdi/vdiConfig.json"
        vdietc="/usr/lib/linuxmuster-linbo-vdi/etc"
        python_version=$(basename $(readlink -f /usr/bin/python3))

        # circumvent missing .installed files in package. Can be removed later
        #if [ -f /etc/linuxmuster/.secret/administrator ]; then
        #    touch $vdietc/.installed
        #fi

        if [ ! -f $vdietc/.installed ];
        then
            echo "---------------------------------------------------------------"
            echo "Installing linuxmuster-linbo-vdi"
            echo "---------------------------------------------------------------"

            # do first install
            /usr/bin/python3 -m pip install -U pip #distribute
            hash -r
            /usr/bin/python3 -m pip install -r $vdietc/requirements.txt
            echo "Copy default config files for linbo vdi"
            mkdir -p /etc/linuxmuster/linbo-vdi/
            #
            if [ -f $vdicfg ];then
                echo "Backing up vdiConfig.json"
                cp -a $vdicfg $vdicfg.bak
            fi
            echo "Writing linuxmuster default linbo vdi config $vdicfg"
            cp -rf $vdietc/template-vdiConfig.json $vdicfg

            # systemctl einrichten und starten
            #echo "Configure systemctl.."
            systemctl daemon-reload
            systemctl enable linuxmuster-linbo-vdi
            #systemctl start linuxmuster-linbo-vdi

            # set already installed flag
            touch $vdietc/.installed
            echo "---------------------------------------------------------------"
            echo "linuxmuster-linbo-vdi is now installed !"
            echo ""
            echo "if you want to use vdi server than confiure /etc/linuxmuster/linbo-vdi/startconfig.json"
            echo "the config an start the service with systemctl start linuxmuster-linbo-vdi"
            echo "---------------------------------------------------------------"
        else
            # do update
            echo "---------------------------------------------------------------"
            echo "Updating linuxmuster-linbo-vdi"
            echo "---------------------------------------------------------------"
            echo "Stop linuxmuster-linbo-vdi"

            systemctl is-active --quiet linuxmuster-linbo-vdi
	        runbefore=$?
            
            # stop service if running before
            if [ $runbefore -eq 0 ]
                echo "Stop linuxmuster-linbo-vdi service"
                systemctl stop linuxmuster-linbo-vdi
            fi

            # Always backup config file if things are going bad
            echo "Backing up vdiConfig.json"
            cp -a $vdicfg $vdicfg.bak

            # Requirements must always be checked
            /usr/bin/python3 -m pip install -r $vdietc/requirements.txt

            # start linbo-vdi
            echo "Reload linuxmuster-linbo-vdi service"
            systemctl daemon-reload

            # start service if running before
            if [ $runbefore -eq 0 ]
             then
              echo "Start linuxmuster-linbo-vdi service"
              systemctl start linuxmuster-libo-vdi
            fi

            echo "---------------------------------------------------------------"
            echo "Updating linuxmuster-linbo-vdi ..done"
            echo "---------------------------------------------------------------"
        fi
    ;;
    upgrade|abort-upgrade)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#

exit 0
